# makefile (invoked with 'make') is a basic build system for C language
# CMake and Scons (Python) are proper build systems used by real projects
all:
	clang main.c -o grep && \
	./grep -i -w "את" ../examples/3-wchar_grep.txt
