# makefile (invoked with 'make') is a basic build system for C language
# CMake and Scons (Python) are proper build systems used by real projects
all:
	gcc grep.c -o grep; ./grep -i "hello" input.txt;
