# makefile (invoked with 'make') is a basic build system for C language
# CMake and Scons (Python) are proper build systems used by real projects
all:
	clang grep.c -o grep && \
	./grep -i -w "the" ../examples/1-basic_grep.txt
